version: '3.8'

services:
  ton-challenge-api:
    container_name: ton-challenge-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: $PORT
    command: sh -c "yarn build && yarn typeorm migration:run && yarn start:docker"
    environment:
      PORT: 3000
      COUNTAPI_URL: https://api.countapi.xyz
      COUNTAPI_NAMESPACE: ton-challenge
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: database
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: postgres
      TYPEORM_DATABASE: ton_challenge_db
      TYPEORM_PORT: 5432
      TYPEORM_LOGGING: "true"
      TYPEORM_ENTITIES: ./build/src/models/*.js
      TYPEORM_MIGRATIONS: ./build/src/database/migrations/*.js
      TYPEORM_MIGRATIONS_DIR: ./build/src/database/migrations
    stdin_open: true
    depends_on:
      - database
    networks:
      - default
    ports:
      - "${PORT}:${PORT}"
    restart: on-failure
  database:
    image: postgres
    container_name: ton-challenge-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ton_challenge_db
    networks:
      - default
