version: '3.8'

services:
  ton-challenge-api:
    container_name: ton-challenge-api
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "yarn typeorm migration:run && yarn start"
    environment:
      API_PORT: 3001
      COUNTAPI_URL: https://api.countapi.xyz
      COUNTAPI_NAMESPACE: ton-challenge
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: database
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: postgres
      TYPEORM_DATABASE: ton_challenge_db
      TYPEORM_PORT: 5432
      TYPEORM_LOGGING: "true"
      TYPEORM_ENTITIES: ./src/models/*.ts
      TYPEORM_MIGRATIONS: ./src/database/migrations/*.ts
      TYPEORM_MIGRATIONS_DIR: ./src/database/migrations
    stdin_open: true
    depends_on:
      - database
    networks:
      - default
    ports:
      - ${API_PORT}:${API_PORT}
    restart: on-failure
  database:
    image: postgres
    container_name: ton-challenge-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ton_challenge_db
    networks:
      - default
